import React from 'react';
import { Bell, CheckCheck, AlertTriangle, Info, XCircle, Trash2 } from 'lucide-react';
import { useAlertsContext } from '../context/AlertsContext';
import { useAuth } from '../context/AuthContext';
import { PageHeader, SeverityBadge, Spinner, EmptyState } from '../components/shared/UI';
import toast from 'react-hot-toast';
import { formatDistanceToNow } from 'date-fns';
import clsx from 'clsx';

const SeverityIcon = ({ severity }) => {
  if (severity === 'critical') return <XCircle size={16} className="text-red-400" />;
  if (severity === 'warning')  return <AlertTriangle size={16} className="text-amber-400" />;
  return <Info size={16} className="text-brand-400" />;
};

export default function AlertsPage() {
  const { alerts, unreadCount, markRead, markAllRead, deleteAlert } = useAlertsContext();
  const { user } = useAuth();
  const canDelete = ['superadmin', 'ministry'].includes(user?.role);

  const handleMarkAllRead = async () => {
    try {
      await markAllRead();
      toast.success('All alerts marked as read');
    } catch {
      toast.error('Failed to update alerts');
    }
  };

  const handleDelete = async (e, id) => {
    e.stopPropagation();
    try {
      await deleteAlert(id);
      toast.success('Alert deleted');
    } catch {
      toast.error('Failed to delete alert');
    }
  };

  return (
    <div className="space-y-5">
      <PageHeader
        title="Alerts & Notifications"
        subtitle={`${unreadCount} unread alert${unreadCount !== 1 ? 's' : ''}`}
        actions={
          unreadCount > 0 && (
            <button onClick={handleMarkAllRead} className="btn-ghost flex items-center gap-2 text-sm">
              <CheckCheck size={14} /> Mark all read
            </button>
          )
        }
      />

      <div className="space-y-2">
        {alerts.length === 0 ? (
          <div className="card">
            <EmptyState icon={Bell} title="No alerts" desc="You're all caught up!" />
          </div>
        ) : (
          alerts.map((alert) => (
            <div
              key={alert._id}
              onClick={() => !alert.isRead && markRead(alert._id)}
              className={clsx(
                'card p-4 flex items-start gap-4 transition-all duration-200',
                !alert.isRead
                  ? 'border-slate-700 cursor-pointer hover:border-slate-600'
                  : 'opacity-60',
              )}
            >
              <div className={clsx(
                'w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0',
                alert.severity === 'critical' ? 'bg-red-900/40' :
                alert.severity === 'warning'  ? 'bg-amber-900/40' : 'bg-brand-900/40'
              )}>
                <SeverityIcon severity={alert.severity} />
              </div>

              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-2">
                  <div className="font-medium text-slate-200 text-sm">{alert.title}</div>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    <SeverityBadge severity={alert.severity} />
                    {!alert.isRead && (
                      <div className="w-2 h-2 rounded-full bg-brand-400" />
                    )}
                    {canDelete && (
                      <button
                        onClick={(e) => handleDelete(e, alert._id)}
                        className="ml-1 text-slate-600 hover:text-red-400 transition-colors"
                        title="Delete alert"
                      >
                        <Trash2 size={13} />
                      </button>
                    )}
                  </div>
                </div>
                <p className="text-sm text-slate-400 mt-0.5">{alert.message}</p>
                <div className="flex items-center gap-3 mt-2">
                  {alert.office && (
                    <span className="text-xs text-slate-500">{alert.office.name}</span>
                  )}
                  <span className="text-xs text-slate-600">
                    {formatDistanceToNow(new Date(alert.createdAt), { addSuffix: true })}
                  </span>
                  {alert.autoGenerated && (
                    <span className="badge-gray text-[10px]">Auto</span>
                  )}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
