const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema(
  {
    office: { type: mongoose.Schema.Types.ObjectId, ref: 'Office' }, // null = all offices
    type: {
      type: String,
      enum: ['low_performance', 'no_submission', 'budget_overrun', 'target_breach', 'custom'],
      required: true,
    },
    severity: { type: String, enum: ['info', 'warning', 'critical'], default: 'info' },
    title: { type: String, required: true },
    message: { type: String, required: true },
    isRead: { type: Boolean, default: false },
    readBy: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    autoGenerated: { type: Boolean, default: false },
    resolvedAt: Date,
  },
  { timestamps: true }
);

module.exports = mongoose.model('Alert', alertSchema);
