const Activity = require('../models/Activity');
const Alert = require('../models/Alert');

// GET /api/activities
exports.getActivities = async (req, res) => {
  try {
    const { officeId, category, status, from, to, page = 1, limit = 20 } = req.query;
    const filter = {};
    if (officeId) filter.office = officeId;
    if (category) filter.category = category;
    if (status) filter.status = status;
    if (from || to) {
      filter.date = {};
      if (from) filter.date.$gte = new Date(from);
      if (to) filter.date.$lte = new Date(to);
    }

    // Scoped to user's office if not ministry-level
    if (['office_admin', 'office_staff'].includes(req.user.role) && req.user.office) {
      filter.office = req.user.office._id;
    }

    const total = await Activity.countDocuments(filter);
    const activities = await Activity.find(filter)
      .populate('office', 'name code city')
      .populate('submittedBy', 'name')
      .sort({ date: -1 })
      .skip((page - 1) * limit)
      .limit(parseInt(limit));

    res.json({ activities, total, page: parseInt(page), pages: Math.ceil(total / limit) });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// POST /api/activities
exports.createActivity = async (req, res) => {
  try {
    const data = { ...req.body, submittedBy: req.user._id };
    if (['office_admin', 'office_staff'].includes(req.user.role)) {
      data.office = req.user.office._id;
    }
    const activity = await Activity.create(data);
    const populated = await activity.populate('office', 'name code city');

    // Real-time broadcast
    const io = req.app.get('io');
    io.emit('activity:new', populated);

    // Auto-alert if delayed
    if (data.status === 'Delayed') {
      const office = populated.office;
      const alert = await Alert.create({
        office: office._id,
        type: 'target_breach',
        severity: 'warning',
        title: `Delayed activity at ${office.name}`,
        message: `"${data.activityName}" is marked as delayed.`,
        autoGenerated: true,
      });
      io.emit('alert:new', alert);
    }

    res.status(201).json({ activity: populated });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// PUT /api/activities/:id
exports.updateActivity = async (req, res) => {
  try {
    const activity = await Activity.findById(req.params.id);
    if (!activity) return res.status(404).json({ message: 'Activity not found' });

    // office_admin can only edit activities of their own office
    if (req.user.role === 'office_admin') {
      if (activity.office.toString() !== req.user.office._id.toString()) {
        return res.status(403).json({ message: 'Not allowed to edit activities of another office' });
      }
    }

    const updated = await Activity.findByIdAndUpdate(req.params.id, req.body, {
      new: true, runValidators: true,
    }).populate('office', 'name code city');

    const io = req.app.get('io');
    io.emit('activity:updated', updated);
    res.json({ activity: updated });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// DELETE /api/activities/:id
exports.deleteActivity = async (req, res) => {
  try {
    const activity = await Activity.findById(req.params.id);
    if (!activity) return res.status(404).json({ message: 'Activity not found' });

    // office_admin can only delete activities of their own office
    if (req.user.role === 'office_admin') {
      if (activity.office.toString() !== req.user.office._id.toString()) {
        return res.status(403).json({ message: 'Not allowed to delete activities of another office' });
      }
    }

    await activity.deleteOne();
    req.app.get('io').emit('activity:deleted', { id: req.params.id });
    res.json({ message: 'Activity deleted' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

